# Python 语法 Error

> 原文:[https://www.educba.com/python-assertionerror/](https://www.educba.com/python-assertionerror/)

![Python AssertionError](../Images/6524cd70e33b8a4ddca73ac1a04cbd87.png)

<noscript><img class="alignnone size-full wp-image-373034" src="../Images/6524cd70e33b8a4ddca73ac1a04cbd87.png" alt="Python AssertionError" width="900" height="500" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Python-AssertionError.jpg 900w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Python-AssertionError-300x167.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Python-AssertionError-768x427.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Python-AssertionError.jpg"/></noscript>

## Python AssertionError 简介

编程中的一个概念是，在运行模块之前，用户在编写代码时使用 assert 语句将条件定义为真，这称为断言，如果条件为真，控制将移动到代码中的下一行；否则，如果条件为假，程序将停止运行，并返回 Python AssertionError 异常，无论程序是用哪种编程语言实现的， assert 语句的功能保持不变，它是一个独立于语言的概念，但是对于不同的编程语言，语法是不同的。

### 句法

Python AssertionError 的语法如下:

<small>网页开发、编程语言、软件测试&其他</small>

`assert condition, error_message(optional)`

### Python 中的 AssertionError 是如何工作的？

Python 语言有一个内置的 assert 语句，使用它我们可以创建基于逻辑断言的简单调试消息输出。当 assert 语句失败时，会引发 AssertionError 异常。BaseException 类是 Python 中所有异常类的基础。Exception 类继承自 BaseException 类，而 base exception 类又是 AssertionError 类的基类。每当在代码中使用 assert 语句时，都应该有适当的异常处理代码来处理 assert 语句的失败。程序员编写的错误消息将由 python 中的默认异常处理程序打印，或者错误也可以在没有任何错误消息的情况下处理。

### 实现 Python AssertionError 的示例

下面是提到的例子:

#### 示例#1

Python 程序演示了将开尔文温度转换为华氏度温度的程序中的断言错误:

**代码:**

```
#!/usr/bin/python
#a function is defined to convert the temperature in degrees kelvin to degrees Fahrenheit to which the temperature is passed as a parameter
def convertKelToFah(Temp):
#This program demonstrates assertion error while converting the temperature in degrees kelvin to temperature in degrees Farhenheit
#assert statement is used to check if the temperature is below zero and an exception is thrown if a negative parameter is passed to it
assert (Temp >= 0),"The temperature is below zero and it is really cold!"
#the converted value of temperature in degrees kelvin to degrees Fahrenheit is returned
return ((Temp-273)*1.8)+32
#temperature value 300 is passed to the function to convert it from degrees kelvin to degrees Fahrenheit
print convertKelToFah(300)
#temperature value 350.50 is passed to the function to convert it from degrees kelvin to degrees Fahrenheit and the integer value is returned
print int(convertKelToFah(350.50))
#temperature value -10 is passed to the function to convert it from degrees kelvin to degrees Fahrenheit and the exception is thrown
print convertKelToFah(-10) 
```

**输出:**

![Python AssertionError1](../Images/3dba17f26c10d06b616ec0b34e058f54.png)

<noscript><img class="alignnone wp-image-372787 size-full" src="../Images/3dba17f26c10d06b616ec0b34e058f54.png" alt="Python AssertionError1" width="550" height="145" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Python-AssertionError1.jpg 550w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Python-AssertionError1-300x79.jpg 300w" sizes="(max-width: 550px) 100vw, 550px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Python-AssertionError1.jpg"/></noscript>

**解释:**在上面的程序中，定义了一个函数，将开尔文温度转换为华氏温度，并将温度作为参数传递给该函数。然后，使用 assert 语句检查温度是否低于零度，如果向其传递负参数，则会引发异常。然后返回从开尔文到华氏温度的转换值。然后，温度值 300 被传递给该函数，以将其从开氏度转换成华氏度。然后将温度值 350.50 传递给函数，将其从开氏度转换为华氏度，并返回整数值。然后将温度值-10 传递给函数，将其从开氏度转换为华氏度，并引发异常。程序的输出显示在上面的快照中。

#### 实施例 2

演示断言错误的 Python 程序，程序中有一条错误消息:

**代码:**

```
#This program demonstrates the Assertion Error with error message.
#a variable is defined to store an integer value
x = 1
#a variable is defined to store an integer value
y = 0
#assert statement is used to check if the second integer value is not equal to zero else error message "The operation is invalid because the denominator cannot be zero" is printed
assert y != 0, "The operation is invalid because the denominator cannot be zero"
#Otherwise the result of first integer divided by the second integer is printed
print(x / y) 
```

**输出:**

![Python AssertionError2](../Images/8b6f7e691c808be2998e837beec85d98.png)

<noscript><img class="alignnone wp-image-372788 size-full" src="../Images/8b6f7e691c808be2998e837beec85d98.png" alt="Python AssertionError2" width="557" height="65" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Python-AssertionError2.jpg 557w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Python-AssertionError2-300x35.jpg 300w" sizes="(max-width: 557px) 100vw, 557px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Python-AssertionError2.jpg"/></noscript>

**解释:**在上面的程序中，打印了断言错误的错误消息。首先，定义一个变量来存储一个整数值。然后，再次定义一个变量来存储另一个整数值。然后使用 assert 语句检查第二个整数值是否不等于零，否则将显示错误消息“操作无效，因为分母不能为零”。否则，打印第一个整数除以第二个整数的结果。程序的输出显示在上面的快照中。

### 避免 Python 中断言错误的步骤

*   我们可以使用-O 标志来禁用流程中出现的所有 assert 语句。通过禁用流程中的 assert 语句，assert 语句后面的语句也不会被执行。
*   我们还可以利用环境变量来设置一个标志，该标志也禁用 assert 语句。通过使用它，所有继承或使用该环境的进程都将受到影响。
*   我们可以确保程序中的控制流没有到达断言语句，或者断言错误可以被捕获，并且从这一点开始，断言错误被处理，程序的正常流恢复。
*   我们可以通过使用-O 打开基本的优化，它将字节码文件或编译文件的文件扩展名改为。pyc 的 pyo。
*   我们还可以设置 PYTHONOPTIMIZE 选项，如果该选项设置为非空字符串，这与使用-O 选项相同。如果 PYTHONOPTIMIZE 设置为整数，则与多次使用-O 相同。

### 结论

在本教程中，我们通过定义了解了 Python 中断言错误的概念，Python 中断言错误的语法，通过编程示例了解了 Python 中断言错误的工作原理，以及它们的输出和避免 Python 中断言错误的步骤。

### 推荐文章

这是 Python AssertionError 的指南。在这里，我们讨论 Python AssertionError 的适当语法介绍，它是如何工作的，以及相应的例子。您也可以浏览我们的其他相关文章，了解更多信息——

1.  [Python 单元测试](https://www.educba.com/python-unit-test/)
2.  [Python 关键词](https://www.educba.com/python-keywords/)
3.  [Python 异常处理](https://www.educba.com/python-exception-handling/)
4.  [Python argparse](https://www.educba.com/python-argparse/)

<footer class="entry-footer">

<aside class="sidebar sidebar-primary widget-area" role="complementary" aria-label="Primary Sidebar">Primary Sidebar</aside>

</footer>