# Python 中的回溯

> 原文：<https://www.educba.com/traceback-in-python/>

![Traceback in Python](img/e3f41833caea4aa0ecbf3b6f2101c3ca.png)



## Python 中回溯的定义

python 中的回溯提供了解决在 Python 程序执行期间发生的未处理异常的关键。该工具列出了异常的性质、对异常的清楚解释，以及以相反的执行顺序列出了触发异常发生的程序段的细节。

文件名、模块名、行号以及回溯模块显示的确切代码有助于开发人员追溯异常的原因，方法是将各种程序步骤链接起来，对准杀手行并纠正它们以实现无错误执行。回溯步骤与 Python 解释器的操作步骤完全匹配，它提高了开发人员快速解决程序中问题的效率。

<small>网页开发、编程语言、软件测试&其他</small>

**语法:**

python 显示的追溯细节包含几个部分，其语法是:

```
Traceback (most recent call last)
Program segment (File name, Line no, module name, exact code) executed first
Program segment (File name, Line no, module name, exact code) executed second
                                                ….
Program segment (File name, Line no, module name, exact code) executed last
Exception name: Detailed exception message 
```

典型的回溯看起来像

Traceback(最近一次调用 last): Traceback 头

第一个被执行的代码

文件“main.py”，第 23 行，在模块 1 中，文件名 main.py，第 23 行，模块 1。
显示精确代码-1 代码

处决名单上的第二名

文件“main.py”，第 20 行，在模块 2 中，文件名 main.py，第 23 行，模块 2。
显示准确的代码-2 代码

执行列表的最后一项

文件“main.py”，第 17 行，在模块 3 中，文件名 main.py，第 23 行，模块 3。
显示确切的代码-3 代码。

索引错误:列表索引超出范围异常名称:详细信息

### 回溯是如何工作的？

当 Python 程序执行过程中出现异常时，python 会生成回溯。python 程序在执行时遇到问题有两种情况。

一个是语法错误。如果程序编码不正确，程序在编译时就会出错。开发人员需要编写正确的代码；然后，只有程序会前进到下一行。

二是被称为异常的逻辑错误。这种错误只在执行过程中发生，并且只有当程序中出现异常情况时才会出现。异常情况的发生是由于提供了错误的数据，而程序不是为管理无关的情况而设计的。

python 中有几个内置的异常，下面列出了其中一些:

1.**ZeroDivisionError**–如果某个值被零除，就会出现此错误。除法中分母为零。
2。**ImportError**–当调用的模块在其库中不可用，程序无法执行时，Python 抛出这个异常。
3。**indentation error**–缩进不正确时抛出异常。像 If，While，For 这样的条件语句需要遵循一定的缩进，如果没有遵循，就会出现这种错误。
4。IndexError–当引用的索引溢出程序中定义的最大限制时，将抛出该异常。
5。**key error**–当在映射表或字典中找不到引用的键时，Python 会触发该异常。
6。**assertion error**–当一个条件在执行前被 using Assert 语句声明为真，并在模块执行过程中滑入假条件时，抛出该异常。如果发现这种情况，程序将停止执行。
7。**name error**–如果试图引用程序中未定义的变量或函数，Python 会抛出此错误。如果局部变量被引用到其边界条件之外，就会发生此错误。8。**attribute error**–如果试图对一个与其原始属性相矛盾的变量赋值，就会出现这种错误。对整数变量进行字符串赋值会导致此错误，反之亦然。9。**type error**–当试图对变量进行错误操作时，Python 会抛出这个异常。对字符串变量进行算术运算或对整数变量进行字符串运算会导致此错误。10。MemoryError 当程序由于创建了太多的内存空间而超出了分配给它的内存时，就会出现这种错误情况。

开发人员将不得不使用错误细节，跟踪导致错误的代码步骤，理解问题并相应地纠正程序。

### Python 中的回溯示例

**1** 。在下面的例子中，有一条规定是对 1-4 月的前四个月的月份描述进行解码，任何超出这一范围的内容都会导致索引错误。

```
# Program to decode month code of the first four months in the year 
mthdesc = ["jan","feb","mar","apr"] # four month description is the table

def decodemth(mm): # Function decodemth to decode
    print (mthdesc[mm]) # calls table, decodes, prints                                  

def src(): # Working function src
    monthcode =input ("Month code Please ") # Accepts month code
    monthcode = int(monthcode) # Converts it into intger
    monthcode = monthcode -1  # Adjust the offset
    decodemth(monthcode)  # Calls the decodemth function

src() # Calling working function 
```

当程序执行时，它会提示月份代码。各种输入下的截图。

月份代码= 02

![Traceback in Python 1](img/9ced68e31d12286e5010d485efb4e93d.png)



月份代码= 04

![Traceback in Python 2](img/abef242b4623ea336777a6fe05de010f.png)



月份代码= 08(超出边界条件)

![Traceback in Python 3](img/3686a0fa0ed28b474a92251999efd647.png)



引发的错误超出索引范围。要执行的第一行是第 13 行，它调用 src()模块。第二行将在 src()模块的第 11 行执行，它调用另一个模块 decodemth(monthcode)。第 5 行中要执行的第三行也是最后一行，它解码并打印，这是抛出错误的地方。

**2** 。在此示例中，尝试对字符串进行算术运算，并返回类型错误

```
# Program to decode month code of the first four months in the year 
mthdesc = ["jan","feb","mar","apr"]  # four month description is the table

def decodemth(mm): # Function decodemth to decode
    print (mthdesc[mm]+1 )   # calls table, decodes, prints                                  

def src():  # Working function src
    monthcode =input ("Month code Please ") # Accepts month code
    monthcode = int(monthcode) # Converts it into intger
    monthcode = monthcode -1 # Adjust the offset
    decodemth(monthcode) # Calls the decodemth function

src() 
```

在执行月份代码 01 的过程中，它给出类型错误并跟踪到第 13 行

![Traceback in Python 4](img/8c1ccf5f5de1c2a9b6e12b73e025f565.png)



**3** 。缩进错误。在功能划分下，各行不缩进

```
def Division():
A = Num / Den
print ("Quotient ", A)

Num = int (input ("numerator "))
Den = int (input ("denominator "))

Division() 
```

![output 1](img/32faf60c605c858f3261598b1a542e48.png)



**4** 。除以零误差

```
def Division():
A = Num / Den
print ("Quotient ", A)
Num = int (input ("numerator "))
Den = int (input ("denominator "))
Division()
```

当程序以 10 为分子，5 为分母执行时，它会正确地给出结果。

![output 2](img/4321481deb199de6060e30a4d9381d4e.png)



当程序以 10 为分子，0 为分母执行时，它会给出一个错误。

![output 3](img/9825bb68dacf31b759f353a14dd963e7.png)



### 结论

回溯提供了许多信息、方法和手段来调试任何错误、定位根本原因并纠正它们，以实现 Python 程序的无错误执行。

### 推荐文章

这是 Python 中的回溯指南。在这里，我们讨论定义，语法，如何追溯工作？示例和代码实现。您也可以看看以下文章，了解更多信息–

1.  [BFS 算法 Python](https://www.educba.com/bfs-algorithm-python/)
2.  [Lisp vs Python](https://www.educba.com/lisp-vs-python/)
3.  [Python 中的多态性](https://www.educba.com/polymorphism-in-python/)
4.  [树遍历 Python](https://www.educba.com/tree-traversal-python/)





