# VB.NET 的异常处理

> 原文:[https://www.educba.com/exception-handling-in-vb-dot-net/](https://www.educba.com/exception-handling-in-vb-dot-net/)

![Exception Handling in VB.NET](../Images/55a0cd349ce99794fc7cdd3593745c48.png)

<noscript><img class="alignnone size-full wp-image-418906" src="../Images/55a0cd349ce99794fc7cdd3593745c48.png" alt="Exception Handling in VB.NET" width="900" height="500" srcset="https://cdn.educba.com/academy/wp-content/uploads/2019/10/Exception-Handling-in-VB.NET_.jpg 900w, https://cdn.educba.com/academy/wp-content/uploads/2019/10/Exception-Handling-in-VB.NET_-300x167.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2019/10/Exception-Handling-in-VB.NET_-768x427.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2019/10/Exception-Handling-in-VB.NET_.jpg"/></noscript>

## Vb.Net 异常处理简介

以下文章“VB.NET 的例外处理”提供了在 VB.Net 处理例外的详细概述。欢迎来到 VB.NET 异常处理的话题。让我们了解什么是异常处理，不同的异常是如何发生的，以及我们如何处理这些异常。异常发生在我们运行一个程序时，一个错误被捕获并导致一个异常，这个异常可以是系统异常，也可以是应用程序异常。我们将在异常类中进一步了解这一点。在这个主题中，我们将学习 about 中的异常处理。

### Vb.Net 异常处理的关键词

based 的异常处理基于四个关键字的使用，如 try、catch、finally 和 throws。

<small>网页开发、编程语言、软件测试&其他</small>

*   **Try:**Try 块是在应用程序中生成不同异常的代码块。为了处理 try 块中抛出的异常，我们使用 catch 块。因此，try 块后面总是跟着一个或多个 catch 块。
*   **Catch:**Catch 块是包含语句的代码块，这些语句通过在出现问题的语句上使用异常处理程序来处理异常。catch 块主要是异常库中定义的不同异常类对异常的处理。
*   **Finally:**Finally 块是一个包含语句的代码块，这些语句是无论异常是否抛出都要执行的强制语句。假设我必须打开一个文件，读取文件，写入文件，然后关闭文件。在 try 块中，语句类似于打开一个文件、读取一个文件和写入一个文件，这些语句可能会也可能不会引发异常，但是在程序结束之前需要关闭该文件。因此，最后一个块总是有关闭文件、关闭数据库连接、关闭程序等语句。
*   **Throw:** 当一个问题发生时，这个语句抛出一个异常。此异常可以是内置的或用户定义的异常。

**语法:**

Try-Catch 块的代码如下所示

```
Try
Catch <Exception Name> As <Exception Type>
[Catch1 Statements]
Catch <Exception Name> As <Exception Type>
[Catch2 Statements]
Catch <Exception Name> As <Exception Type>
[Catch3 Statements]
Finally
[Finally Statements]
End Try
```

这里，在上面的语法中显示了不止一个 catch 块来捕获由 try 块引发的不同类型的异常。try 块抛出的异常可能不止一个，而只有一个 catch 块可用，那么为了捕捉所有的异常，我们需要一个或多个 catch 语句。因此，我们用上面的语法写了不止一个 catch 语句。

### VB.NET 的例外类别

正如在上面的陈述中已经提到的。异常有不同的类型，这些只是类。继承这些类的父类是 System.Exception。

主要有两个例外

1.  系统。系统异常
2.  系统。应用程序异常

系统。SystemException 是一个用于所有内置系统异常的类，或者我们可以说，当运行时出现错误时，系统异常类如 DivideByZeroException、IndexOutOfRangeException、StackOverflowException 被实例化。

系统。ApplicationException 是一个执行由程序员或开发人员在应用程序中定义的异常的类。它抛出一个用户定义的异常，这个异常是从这个系统派生的。应用程序异常类。

让我们看看几个 VB.NET 异常类及其用法。

*   **系统。IndexOutOfRangeException:** 这个异常处理由数组索引超出范围引起的错误。假设我们有一个 5 数组长度的数组，我们循环 6 次，第 6 次程序将通过 IndexOutOfRangeException。
*   **系统。DivideByZeroException:** 这个异常处理一个数被零除时产生的错误，这违反了一个数被零除会导致程序异常终止的普遍规则。
*   **系统。FormatException:** 这个异常处理当[用户在被要求输入数字或整数时输入](https://www.educba.com/java-user-input/)一个字符或字符串所导致的错误。假设用户需要输入 5，但是输入说“y ”,那么这个异常就会发生。

### VB.NET 的异常处理示例

以下是一些例外情况的解释。现在让我们通过例子来学习如何在 VB.Net 处理这些异常

#### 示例#1

下面是 DivideByZeroException 的程序及其输出

**代码**

```
Module exceptionProg
Sub division(ByVal n1 As Integer, ByVal n2 As Integer)
Dim res As Integer
Try
res = n1 \ n2
Catch ex As DivideByZeroException
Console.WriteLine("Exception caught: {0}", ex)
Finally
Console.WriteLine("Result: {0}", res)
End Try
End Sub
Sub Main()
division(100, 0)
Console.ReadKey()
End Sub
End Module
```

**输出**

![DivideByZeroException](../Images/5864ac88a835bbd9766e43d557dc4bbe.png)

<noscript><img class="alignnone wp-image-223612 size-full" src="../Images/5864ac88a835bbd9766e43d557dc4bbe.png" alt="DivideByZeroException" width="626" height="177" srcset="https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-1-output.png 626w, https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-1-output-300x85.png 300w" sizes="(max-width: 626px) 100vw, 626px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-1-output.png"/></noscript>

#### 实施例 2

**溢出异常程序**

```
Module OverFlowProg
Sub division(ByVal n1 As Integer, ByVal n2 As Integer)
Dim res As Integer
Try
res = n1 \ n2
Catch ex As DivideByZeroException
Console.WriteLine("Exception caught: {0}", ex)
Finally
Console.WriteLine("Result: {0}", res)
End Try
End Sub
Sub Main()
division(25,777777777777)
Console.ReadKey()
End Sub
End Module
```

**输出**

![Program for OverflowException](../Images/a4be972ce9308e863dae1131a536d819.png)

<noscript><img class="alignnone wp-image-223611 size-full" src="../Images/a4be972ce9308e863dae1131a536d819.png" alt="Program for OverflowException" width="623" height="187" srcset="https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-2-output.png 623w, https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-2-output-300x90.png 300w, https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-2-output-620x187.png 620w" sizes="(max-width: 623px) 100vw, 623px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-2-output.png"/></noscript>

此外，现在让我们创建我们自己定制的异常

在本节目中，我们将检查数字是偶数还是奇数，

**逻辑:**数除以 2，如果结果为 0，则为偶数，否则为奇数。

**程序的代码是**

```
Module EvenorOddNo
Public Class EvenorOddNo : Inherits ApplicationException
Public Sub New(ByVal message As String)
MyBase.New(message)
End Sub
End Class
Public Class Divide
Dim AnyNo As Integer = 55
Dim No As Integer = 2
Sub showNumber()
If (AnyNo Mod No > 0) Then
Throw (New EvenorOddNo("The number is an odd number"))
Else
Console.WriteLine("The number is an even number : {0}", AnyNo)
End If
End Sub
End Class
Sub Main()
Dim obj As Divide = New Divide()
Try
obj.showNumber()
Catch ex As EvenorOddNo
Console.WriteLine("EvenorOddNo: {0}", ex.Message)
End Try
Console.ReadKey()
End Sub
End Module
```

**输出**

![Exception Handling in VB.NET](../Images/0e3cc3a53ab0eed6f03748a9073057a7.png)

<noscript><img class="alignnone wp-image-223610 size-full" src="../Images/0e3cc3a53ab0eed6f03748a9073057a7.png" alt="Exception Handling in VB.NET" width="625" height="125" srcset="https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-2.2-output.png 625w, https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-2.2-output-300x60.png 300w, https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-2.2-output-620x125.png 620w" sizes="(max-width: 625px) 100vw, 625px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-2.2-output.png"/></noscript>

同样，如果我们在上面的程序中输入数字 100(而不是 55)并执行，它将显示以下错误

![example 2.3 output](../Images/a778fd60680b0a7186d5513bd18b9598.png)

<noscript><img class="alignnone size-full wp-image-223609" src="../Images/a778fd60680b0a7186d5513bd18b9598.png" alt="example 2.3 output" width="622" height="113" srcset="https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-2.3-output.png 622w, https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-2.3-output-300x55.png 300w, https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-2.3-output-620x113.png 620w" sizes="(max-width: 622px) 100vw, 622px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2019/10/example-2.3-output.png"/></noscript>

### 结论

希望你已经理解了 VB.NET 中的异常处理这个主题，并且能够在这里提到的不同例子的帮助下掌握

### 推荐文章

这是 VB.NET 异常处理的指南。这里我们讨论 VB.NET 中的异常类和处理异常的样本代码。您也可以看看以下文章，了解更多信息–

1.  [VB.NET 控制着](https://www.educba.com/vb-dot-net-controls/)
2.  [VB.Net 数据类型](https://www.educba.com/vb-net-data-types/)
3.  [Java 中的异常处理](https://www.educba.com/exception-handling-in-java/)
4.  [VB.Net 事件](https://www.educba.com/vb-dot-net-events/)

<footer class="entry-footer">

<aside class="sidebar sidebar-primary widget-area" role="complementary" aria-label="Primary Sidebar">Primary Sidebar</aside>

</footer>