# Java 运行时异常

> 原文:[https://www.educba.com/java-runtimeexception/](https://www.educba.com/java-runtimeexception/)

![Java RuntimeException](../Images/834c10915afb826224721dcee3b53091.png)

<noscript><img class="alignnone size-full wp-image-373242" src="../Images/834c10915afb826224721dcee3b53091.png" alt="Java RuntimeException" width="900" height="500" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException.jpg 900w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-300x167.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-768x427.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException.jpg"/></noscript>

## Java RuntimeException 简介

异常是在 Java 中运行代码时遇到任何错误时抛出的异常。java 中的 RuntimeException 是被称为 Java 编程语言中所有异常的父类的异常，当它们发生时，在程序或应用程序的执行过程中，这些异常要么崩溃，要么崩溃。但是与其他异常相比，这些异常是不同的，不能像其他异常一样通过在代码中指定来捕获。

### Java 中运行时异常的处理

按照 Object-> Throwable-> Exception-> runtime Exception 的顺序属于 Exception 的父类。因此，它可以被称为运行 JVM (Java 虚拟机)的常规操作时抛出的所有异常的超类。这个 RuntimeException 及其子类属于一类称为“未检查异常”的异常。这些不能也不需要在构造函数或方法的子句中指定。

<small>网页开发、编程语言、软件测试&其他</small>

#### Java 中 RuntimeException 的构造函数

下面是 RuntimeException 的构造函数:

**1。RuntimeException ():** 这抛出了一个新的运行时异常，它的详细消息为 null。

**语法:**

```
public RuntimeException()
```

这里的原因不会被初始化，可以通过调用类 throwable . init cause(Java . lang . throwable)来完成。

**2。runtime exception(String msg):**这也抛出了一个新的运行时异常，但是有我们在 Java 代码中提供的已定义的详细消息。

**语法:**

```
public RuntimeException (String msg)
```

和上面的函数一样，默认不会初始化 cause，同样可以通过调用 throwable . init cause(Java . lang . throwable)来完成。这里的 msg 是详细的消息，它将被 Throwable.getMessage()方法保存以供以后检索。

**3。RuntimeException (String msg，Throwable cause):** 这抛出一个新的运行时异常，带有定义的错误消息及其原因。

**语法:**

```
public RuntimeException (String message, Throwable cause)
```

请注意，这里的 msg 不是自动包含的，必须显式指定。这里，原因是从 Throwable.getCause()函数中获取的，这里允许空值，这象征着其原因不存在或未知。

**4。RuntimeException (String msg，Throwable cause，booleanenableSupp，booleanwritableStack):** 这给出了一个新的运行时异常，并详细描述了错误消息、其具体原因、enableSupp(表示是否已启用或禁用其抑制),以及 writableStack(如果已启用或禁用)是其堆栈跟踪。

**语法:**

```
protected RuntimeException (String message,
Throwable cause,
booleanenableSuppression,
booleanwritableStackTrace)
```

这将给出一个新的运行时异常，带有定义的原因和指定的详细消息、原因、抑制是启用还是禁用，以及可写堆栈跟踪是否已启用。这里的消息是我们正在显示的特定消息，原因指示它是否存在，enableSuppression 指示是否允许抑制，writableStackTrace 指定堆栈跟踪是否应该是可写的。

**5。runtime exception(Throwable cause):**这抛出一个新的运行时异常，带有给定的原因和条件的指定详细错误消息(cause==null？null : cause.toString())，它基本上包含了类及其特定的原因消息。

**语法:**

```
public RuntimeException (Throwable cause)
```

原因由 Throwable.getCause()方法保存，以便以后获取，当允许空值时，它表示原因未知。

### Java 中如何避免 RuntimeException？

我们用来避免这种异常的方法叫做异常处理。这是开发人员在编码时应该记住的最基本的事情之一，因为如果发生异常并且不能处理异常，整个代码都将是无用的。

在 Java 中，我们使用某些称为 throw 和 throw 的子句来处理检查过的异常。运行时异常通常是因为输入错误而发生的，并导致 ArrayIndexOutOfBoundsException、IllegalArgumentException、NumberFormatException 或 NullPointerException 等异常。包括代码中的这些错误，处理不会产生任何变化，但是它可以作为一个好的实践用于文档的请求。

我们可以自定义如下运行时异常:

```
public class AuthenticateUser extends RuntimeException {
public AuthenticateUser (String msg) {
super (msg);
}
}
```

### 例子

以下是 4 种主要运行时异常的示例:

#### Example #1 – ArrayIndexOutOfBoundsException

当我们请求一个无效或不可用的数组的索引值时，就会发生这种情况。

**代码:**

```
public class Main
{
public static void main (String[] args)
{
// Random array of numbers
intip[] = {16, 17, 18, 19, 20};
for (inti=0; i<=ip.length; i++)
System.out.println (ip[i]);
}
}
```

**输出:**

![Java RuntimeException Example 1](../Images/249e940914cd365c7ce7f7b161dafa94.png)

<noscript><img class="alignnone size-full wp-image-373089" src="../Images/249e940914cd365c7ce7f7b161dafa94.png" alt="Java RuntimeException Example 1" width="601" height="153" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-Example-1.png 601w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-Example-1-300x76.png 300w" sizes="(max-width: 601px) 100vw, 601px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-Example-1.png"/></noscript>

如本例所示，在输入数组中，其索引值从 0 到 4。但是在这个 for 循环中，检索到的数组长度将是 5，当试图在数组中访问它时，它将在代码运行时抛出 ArrayIndexOutOfBoundsException。

#### 示例 2–IllegalArgumentException

此异常的原因是所提供的参数格式无效。

**代码:**

```
public class Main {
inti;
public void getMark (int score) {
if (score < 0 || score > 100)
throw new IllegalArgumentException (Integer.toString (score));
else
i = score;
}
public static void main (String[] args) {
Main t = new Main ();
t.getMark (30);
System.out.println (t.i);
Main t1 = new Main ();
t1.getMark (120);
System.out.println (t1.i);
}
}
```

**输出:**

![Java RuntimeException Example 2](../Images/2bcced2ac60903d75b0dc1ef140e5795.png)

<noscript><img class="alignnone size-full wp-image-373090" src="../Images/2bcced2ac60903d75b0dc1ef140e5795.png" alt="Java RuntimeException Example 2" width="567" height="104" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-Example-2.png 567w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-Example-2-300x55.png 300w" sizes="(max-width: 567px) 100vw, 567px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-Example-2.png"/></noscript>

这里我们知道百分比值的最大值是 100。因此，当我们将值作为 101 传递时，我们会在运行时得到非法参数异常。

#### 示例 3–数字格式异常

当一个字符串要被转换成一个数值，比如 float 或 integer 值，但是作为输入给出的字符串形式是非法的或不适当的时候，通常会抛出这个异常。

**代码:**

```
public class Main {
// giving input string as null
public static void main (String[] args) {
inti = Integer.parseInt (null);
}
}
```

**输出:**

![NumberFormatException Example 3](../Images/6f6aef9f14aa32bc604738bff78a178e.png)

<noscript><img class="alignnone wp-image-373092 size-full" src="../Images/6f6aef9f14aa32bc604738bff78a178e.png" alt="NumberFormatException Example 3" width="551" height="97" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-Example-3.png 551w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-Example-3-300x53.png 300w" sizes="(max-width: 551px) 100vw, 551px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-Example-3.png"/></noscript>

在这个例子中，我们把要被解析成整数的输入字符串作为 null。因此会引发数字格式异常。

#### 示例 4–NullPointerException

当变量引用的引用对象为空时，会发生此异常。

**代码:**

```
public class Main {
public static void main (String[] args) {
Object reference = null;
reference.toString ();
}
}
```

**输出:**

![NullPointerException Example 4](../Images/d3465c975e940c71bc31d24abbcccf43.png)

<noscript><img class="alignnone wp-image-373093 size-full" src="../Images/d3465c975e940c71bc31d24abbcccf43.png" alt="NullPointerException Example 4" width="493" height="56" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-Example-4.png 493w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-Example-4-300x34.png 300w" sizes="(max-width: 493px) 100vw, 493px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-RuntimeException-Example-4.png"/></noscript>

在本例中，我们创建了一个名为 reference 的对象，它的值为空。正在为某个操作调用同一个对象，因此会引发此错误。

**结论:**运行时异常在运行时抛出，因此在编译时很难被检测到。它们很难处理，throws 子句只能用来定义它们，而不能捕捉它们。

### 推荐文章

这是一个 Java RuntimeException 的指南。这里我们讨论 Java 中的简介和如何避免 RuntimeException，以及它的例子。您也可以浏览我们推荐的其他文章，了解更多信息——

1.  [Java 堆排序简介](https://www.educba.com/heap-sort-in-java/)
2.  [在 Java 中覆盖(示例)](https://www.educba.com/overriding-in-java/)
3.  [c#中迭代器的优缺点](https://www.educba.com/iterators-in-c-sharp/)
4.  [十大 Java 合集面试问题](https://www.educba.com/java-collection-interview-questions/)

<footer class="entry-footer">

<aside class="sidebar sidebar-primary widget-area" role="complementary" aria-label="Primary Sidebar">Primary Sidebar</aside>

</footer>