# 科特林例外

> 原文:[https://www.educba.com/kotlin-exceptions/](https://www.educba.com/kotlin-exceptions/)

![Kotlin Exceptions](../Images/5c73e791f9b058a94cc059d22a89920c.png)

<noscript><img class="alignnone size-full wp-image-549742" src="../Images/5c73e791f9b058a94cc059d22a89920c.png" alt="Kotlin Exceptions" width="900" height="500" srcset="https://cdn.educba.com/academy/wp-content/uploads/2022/08/Kotlin-Exceptions.jpg 900w, https://cdn.educba.com/academy/wp-content/uploads/2022/08/Kotlin-Exceptions-300x167.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2022/08/Kotlin-Exceptions-768x427.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2022/08/Kotlin-Exceptions.jpg"/></noscript>

## Kotlin 异常简介

kotlin 异常是运行时问题之一，主要发生在不满足条件的程序上，它可能是带有方法、变量和其他关键字的默认类，kot Lin 语言主要使用未检查类型的异常，这些异常可以在运行时代码执行时借助 throw 关键字抛出。所以我们可以处理项目所需的自定义异常，kotlin 只支持未检查的异常。所以它会出现在所有它捕捉到的异常下，并且它是通过使用 kotlin 语言编译器检查和执行代码来执行的。

**kot Lin 异常的语法**

<small>网页开发、编程语言、软件测试&其他</small>

Kotlin 语言使用许多默认关键字、变量和其他内置函数来实现基于移动设备的应用程序。与此类似，异常是 catch 块处理的语言中使用的特性之一。

`fun main()
{
try
{
--some logic codes—
}
catch(e:Exception)
{
--some codes—
}
---some logic codes depend upon the requirement---
}`

以上代码是使用 try-catch 块处理异常的基本语法。我们还可以使用 throw 关键字来抛出自定义异常，如果需要的话，这些异常也在 catch 块中处理。

### Kotlin 中的异常是如何工作的？

*   一般来说，异常是由编译器处理的运行时问题，发生在程序上。它可能发生在任何类型中，如内存空间、数组索引越界异常和其他情况。Kotlin 语言接受未经检查的异常，如算术异常、ArrayIndexOutOfBoundExceptions 异常、安全异常和 NullPointer 异常；这些是由 kotlin 语言处理的未经检查的异常。
*   整数大概是用 0 数除的；异常将被抛出并归入算术异常。它还有其他不同类型的异常，如 IOException 等。这些异常是在 kotlin 语言中每个被认为是错误的操作中执行的。如果我们想要创建定制的异常，我们可以创建自己的异常，这些异常通过特定的关键字(如 throw、catch 和 finally 等其他块)进行验证和利用。基于项目需求，每个块都有自己有效的已检查和未检查异常。
*   异常指出了代码中的问题，以使用 jtest 等工具测试原则来捕获索引。我们可以使用关于运行时问题和程序执行的异常处理机制来处理异常。

### 科特林异常的例子

下面给出了 Kotlin 异常的例子:

#### 示例#1

**代码:**

`package one
abstract class Planet(planetname:String){
abstract var name: String
abstract fun planetdetails()
init {
println("Planet name is: $name")
}
fun firstplanet(){
println("Thank you the Planet name is")
}
}
interface commonplanet {
var vars: String
fun earth():String
fun mars() {
println("Have a Nice day users")
}
}
class sun : commonplanet {
override var vars: String = "pluto"
override fun earth() = "jupiter"
}
class venus(planetname:String): Planet(planetname) {
override var name: String = "July"
override fun planetdetails() {
println("Thank you users your Planet is $name")
}
}
fun main() {
val m2 = venus("May")
println("Your current Planet is : ${m2.name}")
m2.planetdetails()
val j = sun()
println("Your latest Planet is = ${j.vars}")
print("Keep on spent the time with our application: ")
j.mars()
print("Nice day users ")
println(j.earth())
try{
println("Thank you users your planet details under exception")
throw Exception("Its having some issue please try later")
println("After getting all the details we got a exception")
}
catch(e: Exception){
println(e)
}
finally{
println("Kindly spent with time with our application and try it again")
}
}`

**输出:**

![java.lang.exception](../Images/d98c6fd657b030cdc330ab881ce63131.png)

<noscript><img class="alignnone wp-image-476570 size-full" src="../Images/d98c6fd657b030cdc330ab881ce63131.png" alt="java.lang.exception" width="613" height="179" srcset="https://cdn.educba.com/academy/wp-content/uploads/2021/05/Kotlin-Exceptions-1.jpg 613w, https://cdn.educba.com/academy/wp-content/uploads/2021/05/Kotlin-Exceptions-1-300x88.jpg 300w" sizes="(max-width: 613px) 100vw, 613px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2021/05/Kotlin-Exceptions-1.jpg"/></noscript>

在上面的例子中，我们使用了 java.lang.exception 之类的普通异常，如果定制的用户输入数据无效，则抛出该数据。

#### 实施例 2

**代码:**

`package one;
class second {
companion object {
const val sample = "Welcomeusers"
}
fun demo() = sample;
var x = 0;
fun demo1(i: Int): Int {
return 6 * i
}
fun demo4(i: Int): Int {
return 6 * i + 1
}
fun demo4(y: Array<Int>, i: Int, j: Int) {
var z = y[i] y[i] = y[j] y[j] = z
}
fun demo4(y: Array<Int>, i: Int) {
var eg = demo1(i);
var eg1 = demo4(i);
var eg2: Int;
if ((eg <= x - 1) && (y[eg] > y[i])) {
eg2 = eg;
} else
eg2 = i
if ((eg1 <= x - 1) && (y[eg1] > y[eg])) {
eg2 = eg1
}
if (eg2 != i) {
demo4(y, i, eg2);
demo4(y, eg2);
}
}
fun demo1(y: Array<Int>) {
x = y.size
for (i in x / 2 downTo 0) {
demo4(y, i)
}
}
fun demo(y: Array<Int>) {
demo1(y)
for (i in y.size - 1 downTo 1) {
demo4(y, i, 0)
x = x - 1
demo4(y, 0)
}
}
}
fun main(arg: Array<String>) {
try{
println("Welcome To My Domain its the second example regarding kotlin exception")
println("Please enter your valuable inputs for to perform the sorting operations:")
var p = readLine()!!.toInt()
println("Enter your input datas so that sorting operation will be performed ")
var y = Array(p, { 0 })
for (i in 0 until p)
y[i] = readLine()!!.toInt()
var q = second();
q.demo(y)
println("Welcome To My Domain its y second sample for regarding the kotlin static concept")
for (i in 0 until p)
print("${y[i]} ")
}
catch(e:Exception)
{
println(e)
}
}`

**输出:**

![Kotlin Exceptions 2](../Images/b491bf41c8e1c263e207e61f1c923c7b.png)

<noscript><img class="alignnone wp-image-476573 size-full" src="../Images/b491bf41c8e1c263e207e61f1c923c7b.png" alt="Kotlin Exceptions 2" width="723" height="166" srcset="https://cdn.educba.com/academy/wp-content/uploads/2021/05/Kotlin-Exceptions-2.jpg 723w, https://cdn.educba.com/academy/wp-content/uploads/2021/05/Kotlin-Exceptions-2-300x69.jpg 300w" sizes="(max-width: 723px) 100vw, 723px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2021/05/Kotlin-Exceptions-2.jpg"/></noscript>

![additional operations like number format exceptions](../Images/d6035dbecf25bc4f1c6315235b6cf2c0.png)

<noscript><img class="alignnone wp-image-476576 size-full" src="../Images/d6035dbecf25bc4f1c6315235b6cf2c0.png" alt="additional operations like number format exceptions" width="691" height="79" srcset="https://cdn.educba.com/academy/wp-content/uploads/2021/05/Kotlin-Exceptions-3.jpg 691w, https://cdn.educba.com/academy/wp-content/uploads/2021/05/Kotlin-Exceptions-3-300x34.jpg 300w" sizes="(max-width: 691px) 100vw, 691px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2021/05/Kotlin-Exceptions-3.jpg"/></noscript>

在第二个例子中，我们在输入字符串值而不是整数时使用了额外的操作，比如数字格式异常。

#### 实施例 3

**代码:**

`package one;
fun main(arg: Array<String>) {
var a= "Welcome Users its a third example regarding exception"
var b = try { a.toInt() } catch (e: NumberFormatException) { "Sorry users it accepts only string values" }
println(b)
a = "89"
b = try { a.toInt() } catch (e: NumberFormatException) { "Thank you users its a string value" }
println(b)
try {
var d = 9 / 0
val f = "Have a Nice Day users"
f.toInt()
} catch (e: ArithmeticException) {
println("Arthimetic Exception")
} catch (e: Exception) {
println("Exception occurred please find the stack trace print using e")
} finally {
println("Thank you for spending the time with us")
}
}`

**输出:**

![sorting operations](../Images/069b2213c3237c8b6b1440801fa509d0.png)

<noscript><img class="alignnone wp-image-476579 size-full" src="../Images/069b2213c3237c8b6b1440801fa509d0.png" alt="sorting operations" width="487" height="86" srcset="https://cdn.educba.com/academy/wp-content/uploads/2021/05/Kotlin-Exceptions-4.jpg 487w, https://cdn.educba.com/academy/wp-content/uploads/2021/05/Kotlin-Exceptions-4-300x53.jpg 300w" sizes="(max-width: 487px) 100vw, 487px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2021/05/Kotlin-Exceptions-4.jpg"/></noscript>

在最后一个例子中，我们计算了排序操作，也做了算术运算，得到了算术异常。

### 结论

在 kotlin 语言中，我们使用额外的操作和特性来实现应用程序；在执行应用程序之后，当输入没有被认证或者对编码逻辑不满意时，我们得到了一些有效的异常和错误。借助异常概念，我们可以遍历异常，并且它还接受一些定制的异常。

### 推荐文章

这是一个 Kotlin 异常的指南。这里我们讨论一下引言，异常在 kotlin 中是如何工作的？和示例。您也可以看看以下文章，了解更多信息–

1.  [科特林范围](https://www.educba.com/kotlin-range/)
2.  [科特林循环](https://www.educba.com/kotlin-loops/)
3.  [科特林构造函数](https://www.educba.com/kotlin-constructors/)
4.  [科特林琴弦](https://www.educba.com/kotlin-string/)

<footer class="entry-footer">

<aside class="sidebar sidebar-primary widget-area" role="complementary" aria-label="Primary Sidebar">Primary Sidebar</aside>

</footer>