# Ruby 重试

> 原文:[https://www.educba.com/ruby-retry/](https://www.educba.com/ruby-retry/)

![Ruby retry](../Images/bff29685ccd6eb86d06f1ee806d96ccb.png)

<noscript><img class="alignnone size-full wp-image-351891" src="../Images/bff29685ccd6eb86d06f1ee806d96ccb.png" alt="Ruby retry" width="900" height="500" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry.jpg 900w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry-300x167.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry-768x427.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry.jpg"/></noscript>

## Ruby 重试简介

在 Ruby 中，retry 语句允许我们从头开始重复完整的循环，这是新的编程技巧，主要是在处理任何事务或任何其他类型的循环时使用 retry 语句，其中循环的每次迭代都应该成功，或者在某些特定的序列中，如果我们发现正在运行的循环的任何迭代有任何问题，我们可以使用 retry 语句从头开始循环，retry 语句总是在循环内部使用，这意味着应该有任何迭代来实现 retry 语句。

### 句法

在下面我们已经为 retry 语句写了一个简单的语法，我们可以用下面的步骤来解释下面的语法。

<small>网页开发、编程语言、软件测试&其他</small>

*   我们对数值运行一个开始循环。这里的数值可以是任何值，从 0 到任何数字。
*   在开始的循环中，我们可以执行一些操作。
*   我们已经编写了一个条件块，它将根据我们的要求检查任何特定的条件。
*   在条件为真或成功的情况下，将引发异常，救援块将发挥其作用。
*   在 rescue 块中，我们正在检查是否调用了 retry 语句，该语句将仅从该点开始循环。
*   我们在使用 retry 时需要非常小心，就好像它不会与正确的逻辑一起使用，并且理解循环可能会无限循环，因为它会不断调用 retry。
*   这里，retry 应该调用一个适当的限制，这意味着它应该重试多少次。

**参见下面的语法进行理解:**

`numericValue.times do |i|
begin`

#在每次迭代中对即将到来的数据执行一些操作

`raise conditional expression #If conditional expression successful simply it will fall into rescue block
rescue`

#这里我们将捕获 begin 块中引发的异常

`retry
end
end`

### Ruby 中的 retry 语句是如何工作的？

您必须访问过电子商务网站，如果您已经下了订单，万一付款失败，可能会有一个重试付款的选项，这将得到一个内部电话。因此，实际上它检查支付调用是成功还是失败，如果支付失败，它将不会发送成功消息，而是在内部调用重试。一般来说，在实际情况下，重试呼叫会有限制，因为假设我们尝试呼叫支付网关，但第一次没有响应，我们再次尝试使用支付网关进行支付。因此，实际上，如果支付网关的网站宕机，我们无法全天重试，因此我们可以设置一些限制。我们需要编写适当的处理重试的逻辑来控制调用的限制。

*   请看下图，我们已经展示了一个简单的流程，在这里我们检查任务是否完成。
*   如果任务成功完成(例如付款完成)，只需结束 begin 块。
*   但是，如果任务没有完成或失败(例如支付失败)，在这种情况下，我们将把我们的调用重定向到 retry 语句，该语句将再次从同一点调用任务。
*   在开始的循环中，我们可以执行一些操作，比如付款等等。
*   我们必须写一个条件来调用重试，我们可以在 raise 和 rescue 的帮助下完成。
*   在条件为真或成功的情况下，将引发异常(raise 是 Ruby 中引发异常的关键字)和 rescue(rescue 是 Ruby 中捕捉由 raise 语句引发的异常的关键字)块将发挥其作用。
*   在图中的救援块内，重试块将被写入救援块内。这意味着 raise 语句将捕获内部救援和内部救援，我们将调用 retry，这将再次调用任务块。
*   我们在使用 retry 时需要非常小心，就好像它不会与正确的逻辑一起使用，并且理解循环可能会无限循环，因为它会不断调用 retry。
*   这里，重试调用应该有一个适当的限制，这意味着应该正确处理重试调用的次数，否则循环可能会无限循环下去。

为了更好地理解，请参见下图:

![Ruby retry - 1](../Images/f1d7a723c536f6a5881cea0f7a8f8fbb.png)

<noscript><img class="alignnone size-full wp-image-351516" src="../Images/f1d7a723c536f6a5881cea0f7a8f8fbb.png" alt="Ruby retry - 1" width="385" height="365" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry-1.png 385w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry-1-300x284.png 300w" sizes="(max-width: 385px) 100vw, 385px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry-1.png"/></noscript>

### 实现 Ruby 重试的示例

下面是提到的例子:

#### 示例#1

下面是一个例子，我们取了任意一个随机数，并在上面运行一个循环来打印这个数，如果这个数大于 7，就抛出一个异常。引发的异常将在救援块内部处理。在 rescue 块中，我们注释了 retry 语句，如果我们启用 retry 块，那么循环将无限期执行。正如我已经提到的，我们需要小心使用重试语句，以避免无限。请按照下面的例子以及输出屏幕。

**代码:**

`numbers =10
numbers.times do |number|
begin
puts "This the iteration number inside begin block #{number}"
raise if number > 7
rescue`

#这里我们使用重试再次呼叫

`puts "Here retry statement will be called as it falls under rescue block #{number}"
#retry
exit
end
end`

**输出:**

![Ruby retry - 2](../Images/54c9be377e38a1049c505e20cc015435.png)

<noscript><img class="alignnone size-full wp-image-351536" src="../Images/54c9be377e38a1049c505e20cc015435.png" alt="Ruby retry - 2" width="582" height="205" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry-2.png 582w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry-2-300x106.png 300w" sizes="(max-width: 582px) 100vw, 582px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry-2.png"/></noscript>

#### 实施例 2

正如我向你提到的，我们需要非常小心地使用重试来避免无限循环。下面是一个例子，在这个例子中，一旦 retry 得到调用，这个循环将无限循环下去，不再执行代码。在使用重试之前，我们需要检查我们的需求。请查看下面的示例以及输出屏幕。

**代码:**

`begin
tryAgain ||= 0
puts "Please try again to execute the code block ##{ tryAgain }"
raise "We are raising exception each time to check tryAgain count"
rescue`

#这里重试语句将处理如果重试值大于 2，它将开始重试，并且不打印任何内容:

`puts "retry will get called"
retry if (tryAgain += 1) < 3
end`

**输出:**

![called](../Images/0c33d537458d8905f3513f3c884c90a8.png)

<noscript><img class="alignnone wp-image-351537 size-full" src="../Images/0c33d537458d8905f3513f3c884c90a8.png" alt="called" width="399" height="127" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry-3.png 399w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry-3-300x95.png 300w" sizes="(max-width: 399px) 100vw, 399px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-retry-3.png"/></noscript>

### 结论

从本教程中，我们了解了 Ruby 的重试，并通过一些重要的例子了解了在现实生活中可以使用重试的地方。我们经历了许多我们可以使用和应该避免使用它的重要情况。

### 推荐文章

这是 Ruby 重试指南。在这里我们讨论一个介绍，语法重试语句是如何用例子来实现的。您也可以浏览我们的其他相关文章，了解更多信息——

1.  [红宝石运算符](https://www.educba.com/ruby-operators/)
2.  [While Ruby 中的循环](https://www.educba.com/while-loop-in-ruby/)
3.  [Ruby 中的循环](https://www.educba.com/loops-in-ruby/)
4.  [红宝石需求](https://www.educba.com/ruby-require/)

<footer class="entry-footer">

<aside class="sidebar sidebar-primary widget-area" role="complementary" aria-label="Primary Sidebar">Primary Sidebar</aside>

</footer>