# Ruby 异常

> 原文:[https://www.educba.com/ruby-exceptions/](https://www.educba.com/ruby-exceptions/)

![Ruby Exceptions](../Images/6d46ba60bec22796d3a8fe8592ba1b5d.png "Ruby Exceptions")

<noscript><img class="alignnone wp-image-351205 size-full" title="Ruby Exceptions" src="../Images/6d46ba60bec22796d3a8fe8592ba1b5d.png" alt="Ruby Exceptions" width="900" height="500" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-Exceptions.jpg 900w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-Exceptions-300x167.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-Exceptions-768x427.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/Ruby-Exceptions.jpg"/></noscript>

## Ruby 异常简介

在 Ruby 中，为了处理意外情况，我们可以使用 begin rescue，这里的意外是指会给代码执行带来问题的情况。例如，如果您调用服务器从数据库获取数据，而数据库关闭或表被删除等，在这种情况下，我们无法对代码做任何事情，但要显示正确的错误消息，我们需要使用 begin 和 catch，并且我们需要知道给定情况下的正确异常类。在许多情况下，如调用其他服务器应用程序，如果服务器停止执行，我们的应用程序可以暂停，所以为了避免这种情况，我们在 Ruby 中使用 begin 和 rescue，我们可以使用默认的 begin 和 end，或者使用 try-catch 关键字本身。

### Ruby 中的异常类

在 Ruby 中发生的任何错误总是属于一些异常类。我们也可以使用 try 来处理异常，让我们举个例子，如果我们想读取一个文件(因为文件可能不在那里)并且文件不在那里，那么将会有一个需要处理的异常，否则代码的进一步执行是不可能的(文件不可用属于一个异常类)。为了更清楚起见，我们再举一个例子，在处理 SQL 查询的情况下，表可能会被删除，如果它无法进一步执行。所以在 Ruby 中，很多类型的异常可能是因为错误的语法，可能是因为错误的操作，等等。Ruby 中有很多例外。

<small>网页开发、编程语言、软件测试&其他</small>

下面给出了 ruby 中的各种异常类和一个例子:

#### 1.中断

Interrupt 是一个从那里暂停执行并开始执行前面代码的类。请看下面的例子，我们只是在循环中取了一个空白的 json，这里整个代码都在 begin 块中，begin 块将检查是否有任何异常，以及是否有任何救援将在 Interrupt 的帮助下发挥作用。

**举例:**

将代码块放入 begin 和 inside rescue 中，我们将获得与异常相关的数据。

**代码:**

`begin
puts "We are printing here moment"
loop {}
rescue Interrupt => e
puts "Here we are looking to the Interrupt exception class"
end`

**输出:**

![ruby exceptions 1](../Images/a67d697e367c02c2c8e5db5032bf9f0d.png "ruby exceptions 1")

<noscript><img class="alignnone wp-image-351039 size-full" title="ruby exceptions 1" src="../Images/a67d697e367c02c2c8e5db5032bf9f0d.png" alt="ruby exceptions 1" width="443" height="115" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-1-1.jpg 443w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-1-1-300x78.jpg 300w" sizes="(max-width: 443px) 100vw, 443px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-1-1.jpg"/></noscript>

#### 2.标准误差

这是 Ruby 中非常常见的异常类，可以显示发生异常的细节。请看下面的例子，我们试图打开一个文件 anyfile.rb，这个文件在目录中并不存在，并且为它生成了一个异常。这里异常的名称是 LoadError。

**举例:**

**代码:**

`require 'anyfile.rb' rescue "Hi"`

**输出:**

![ruby exceptions 2](../Images/d713701ab5238a56ce0a4aafce5c0ea4.png "ruby exceptions 2")

<noscript><img class="alignnone wp-image-351041 size-full" title="ruby exceptions 2" src="../Images/d713701ab5238a56ce0a4aafce5c0ea4.png" alt="ruby exceptions 2" width="922" height="132" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-2.jpg 922w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-2-300x43.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-2-768x110.jpg 768w" sizes="(max-width: 922px) 100vw, 922px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-2.jpg"/></noscript>

#### 3.ArgumentError

当提供的参数不正确时，会发生此错误异常。很多时候，当你调用一个函数的时候，这个函数可以有一些参数，如果参数的数量不匹配，就会有一些异常。在下面的例子中，我们传递了错误数量的参数。

**举例:**

**代码:**

`["ranjan","vijay","ajay"].first(4, 5)`

**输出:**

![ArgumentError](../Images/cf8e8f6d6024a5435822a1083d3603c3.png "ArgumentError")

<noscript><img class="alignnone wp-image-351044 size-full" title="ArgumentError" src="../Images/cf8e8f6d6024a5435822a1083d3603c3.png" alt="ArgumentError" width="921" height="144" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-3.jpg 921w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-3-300x47.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-3-768x120.jpg 768w" sizes="(max-width: 921px) 100vw, 921px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-3.jpg"/></noscript>

#### 4\. KeyError

在任何 has(object)的情况下，如果搜索关键字在给定的散列中不存在，则此错误将作为异常类 keyError 出现。在下面的例子中，我们创建了一个名为 funcData 的对象，并给它分配了一些键值对。在搜索元素 finalFunc 时，如果它不存在，它将显示一个异常错误 keyError。

**举例:**

**代码:**

`funcData = {"testFunc" => :finalFunc}
funcData.fetch("testFunc") #=> :finalFunc
funcData.fetch("finalFunc") #=> KeyError: Here it will raise key not found error`

**输出:**

![ruby exceptions 4](../Images/e5e86d4c3b54d2c6aef73ecb977e03bf.png "ruby exceptions 4")

<noscript><img class="alignnone wp-image-351048 size-full" title="ruby exceptions 4" src="../Images/e5e86d4c3b54d2c6aef73ecb977e03bf.png" alt="ruby exceptions 4" width="811" height="165" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-4.jpg 811w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-4-300x61.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-4-768x156.jpg 768w" sizes="(max-width: 811px) 100vw, 811px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-4.jpg"/></noscript>

#### 5.索引错误

这类似于键错误，这种异常发生在数组的情况下。如果我们试图获取一个数组的索引，而这个索引不可用，就会出现这种错误。在下面的例子中，我们创建了一个数组 indexData，并为它分配了一些数组属性。我们试图搜索它给出结果的各种索引，但一旦我们获取此处不可用的索引，它会显示一个异常错误 IndexError。

**举例:**

**代码:**

`indexData = [:a, :b, :c] indexData.fetch(2)   #=> :b
indexData[4]          #=> nil
indexData.fetch(4)   #=> IndexError: As we can see the Array it does not have element number 4 as its maximum size is less than 4`

**输出:**

![IndexError](../Images/1368591043034f85079e2a47e1f57fd3.png "IndexError")

<noscript><img class="alignnone wp-image-351054 size-full" title="IndexError" src="../Images/1368591043034f85079e2a47e1f57fd3.png" alt="IndexError" width="639" height="112" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-5.jpg 639w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-5-300x53.jpg 300w" sizes="(max-width: 639px) 100vw, 639px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-5.jpg"/></noscript>

#### 6.IOError

在这里，我们尝试读取目录/测试/主机读取失败，然后将生成一个名为 IOError 的错误类异常。在下面的例子中，我们试图打开/test/host 目录。

**举例:**

**代码:**

`File.open("/test/hosts") {|f| f.close; f.read }`

**输出:**

![IOError](../Images/51974bcf78471eedee040027f200965a.png "IOError")

<noscript><img class="alignnone wp-image-351057 size-full" title="IOError" src="../Images/51974bcf78471eedee040027f200965a.png" alt="IOError" width="926" height="157" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-6.jpg 926w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-6-300x51.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-6-768x130.jpg 768w" sizes="(max-width: 926px) 100vw, 926px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-6.jpg"/></noscript>

#### 7.ENOENT

当我们试图读取一个文件而该文件不可用时，就会产生这些类型的异常类。在下面的例子中，我们试图读取一个文件 anyfile.rb，但是这个文件在这里不存在，所以异常的输出将是 ENOENT。

**举例:**

**代码:**

`File.open("anyfile.rb")`

**输出:**

![ruby exceptions 7](../Images/63316faf505d6e09ca28cf5a9ee07371.png "ruby exceptions 7")

<noscript><img class="alignnone wp-image-351060 size-full" title="ruby exceptions 7" src="../Images/63316faf505d6e09ca28cf5a9ee07371.png" alt="ruby exceptions 7" width="927" height="156" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-7.jpg 927w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-7-300x50.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-7-768x129.jpg 768w" sizes="(max-width: 927px) 100vw, 927px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-7.jpg"/></noscript>

#### 8.语法错误

这些类型的异常类通常是你在 Ruby 中编写代码时会遇到的，你会遗漏一些语法，请看下面的例子，我们在这里写了多余的=这没有任何意义，因此我们得到了一个名为 SyntaxError 的异常错误类。

**举例:**

**代码:**

`eval("11+1=20"+2)`

**输出:**

![SyntaxError](../Images/818f39651f84e57eadd7ad9cbd0e8695.png "SyntaxError")

<noscript><img class="alignnone wp-image-351061 size-full" title="SyntaxError" src="../Images/818f39651f84e57eadd7ad9cbd0e8695.png" alt="SyntaxError" width="920" height="168" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-8.jpg 920w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-8-300x55.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-8-768x140.jpg 768w" sizes="(max-width: 920px) 100vw, 920px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/04/ruby-exceptions-8.jpg"/></noscript>

### 结论

从本教程中，我们了解了 Ruby 的异常，了解了 Ruby 的异常类，借助一些重要的例子，我们了解了这些异常类在现实生活中的应用场合，我们浏览了许多重要的异常类以及这些异常类的原因。

### 推荐文章

这是一个 Ruby 异常的指南。这里我们用例子来讨论 ruby 中的引入类和异常类。您也可以看看以下文章，了解更多信息–

1.  [红宝石运算符](https://www.educba.com/ruby-operators/)
2.  [Ruby 中的循环](https://www.educba.com/loops-in-ruby/)
3.  [Ruby 数组方法](https://www.educba.com/ruby-array-methods/)
4.  [Ruby 方法](https://www.educba.com/ruby-methods/)

<footer class="entry-footer">

<aside class="sidebar sidebar-primary widget-area" role="complementary" aria-label="Primary Sidebar">Primary Sidebar</aside>

</footer>